var colors = [
  "aqua",
  "black",
  "blue",
  "fuchsia",
  "gray",
  "green",
  "lime",
  "maroon",
  "navy",
  "olive",
  "orange",
  "purple",
  "red",
  "silver",
  "teal",
  "white",
  "yellow",
];

export default [
  {
    id: 1,
    title: "Great Simple",
    subTitle: "Welcome to Great Simple",
    cta: "Subscribe to Great Simple...",
    titleAv: "GS",
    time: "6:30 PM",
    favorite: false,
    viewed: false,
    color: colors[Math.floor(Math.random() * 10 + 1)],
    selected: true,
  },
  {
    id: 2,
    title: "Great Simple",
    subTitle: "Welcome to Great Simple",
    cta: "Subscribe to Great Simple...",
    titleAv: "GS",
    time: "6:30 PM",
    favorite: false,
    viewed: true,
    color: colors[Math.floor(Math.random() * 10 + 1)],
    selected: false,
  },
  {
    id: 3,
    title: "Dribble",
    subTitle: "New Updates from...",
    cta: "Your status in the eyes of the employer...",
    titleAv: "D",
    time: "6:30 PM",
    favorite: false,
    viewed: true,
    color: colors[Math.floor(Math.random() * 10 + 1)],
    selected: false,
  },
  {
    id: 4,
    title: "Google Play",
    subTitle: "Thank you. You have signed up for a...",
    cta: "Your Google Play Music Order from…",
    titleAv: "GP",
    time: "6:30 PM",
    favorite: false,
    viewed: true,
    color: colors[Math.floor(Math.random() * 10 + 1)],
    selected: false,
  },
  {
    id: 5,
    title: "Dribble",
    subTitle: "Thank you for purchasing!",
    cta: "When you arrive prepared to negotiate...",
    titleAv: "D",
    time: "6:30 PM",
    favorite: false,
    viewed: true,
    color: colors[Math.floor(Math.random() * 10 + 1)],
    selected: false,
  },
];
